### ISSUE TITLE
Dynamic tree generation?

### ISSUE THREAD

**Issue by WavyRancheros** [viliwonka/KDTree#2]
Hi,

I need to index huge datasets, and I need to do it on the fly. That means I can't input all 40 million points all at once, but I want to add 32K points every now and then.

Can KDTree do that? From what I've seen it can only use an array and can only be updated without changing the length of the array.

Best,
Wavy

**Comment by viliwonka** [comment]
Hello!

Right now the tree does not have that functionality. I will see what I can do.

**Comment by viliwonka** [comment]
Ok, I saw the functionality to resize number of points is already there. I pushed the fixes to enable this.

But, whole tree with 40 million points will need to be rebuilt everytime (tree isn't dynamic), everytime you add points.
This can take a too long time to be practical. 

1 million points take around 500ms for rebuilding the tree, so 40 mil would take 20 seconds. (for default parameters> = max points per leaf node is 16. )

Building tree for 32K points takes around 16ms, which is very fast. Would be less, if you increase max points per leaf node.

So I suggest you make chunk of points. Every chunk should have it's own KDTree. This will speed up loading and will build KDTree points only for new points.

But trick is, for querying the points, you will have to query all the chunks (all KDTrees). One query could take around 80-100ms, depends of type of query, but if you have chunked KDTrees, you can easily pararellize the queries.

Hope this answers your question :). I am not sure this project could be fit for 40 million points, GPU might be better suited for this!

**Comment by viliwonka** [comment]
Closing the issue for now.
